services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: echo_app
    environment:
      - NODE_ENV=production
        PORT=${PORT}
