name: Docker CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3

        with:
          context: .
          file: Dockerfile
          push: true
          tags: moabdelazem/echo:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=moabdelazem/echo:cache
          cache-to: type=registry,ref=moabdelazem/echo:cache,mode=max
